before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/ddbrew/main.go
    binary: ddbrew
    ldflags:
      - -s -w -X github.com/shuntaka9576/ddbrew/cli.Version={{ .Version }} -X github.com/shuntaka9576/ddbrew/cli.Revision={{ .ShortCommit }}
    goos:
      - linux
      - darwin
    ignore:
      - goarch: 386
      - goarch: arm64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    name: ddbrew
    github:
      owner: shuntaka9576
      name: homebrew-tap
    url_template: "https://github.com/shuntaka9576/ddbrew/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    homepage: "https://blog.hozi.dev/"
    description: "Simple DynamoDB utility"
    test: |
      system "#{bin}/ddbrew --help"
    install: |
      bin.install "ddbrew"
