before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/ddbrew/main.go
    binary: ddbrew
    ldflags:
      - -s -w -X github.com/shuntaka9576/ddbrew/cli.Version={{ .Version }} -X github.com/shuntaka9576/ddbrew/cli.Revision={{ .ShortCommit }}
    goos:
      - linux
      - darwin
    ignore:
      - goarch: 386
      - goarch: arm64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
